import type { Metadata } from "next"
import "./globals.css"
import { Navbar } from "@/components/common/Navbar"
import Footer from "@/components/common/Footer"
import { auth } from '../auth'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await auth()
  
  return (
    <html lang="en">
      <body>
        <Navbar session={session} />
        {children}
        <Footer />
      </body>
    </html>
  )
}